package net.petersil98.thresh.model.game.match.timeline.event;

public enum EventType {
    ASCENDED_EVENT,
    BUILDING_KILL,
    CAPTURE_POINT,
    CHAMPION_KILL,
    CHAMPION_SPECIAL_KILL,
    CHAMPION_TRANSFORM,
    DRAGON_SOUL_GIVEN,
    ELITE_MONSTER_KILL,
    GAME_END,
    ITEM_DESTROYED,
    ITEM_PURCHASED,
    ITEM_SOLD,
    ITEM_UNDO,
    LEVEL_UP,
    OBJECTIVE_BOUNTY_PRESTART,
    OBJECTIVE_BOUNTY_FINISH,
    PAUSE_END,
    PORO_KING_SUMMON,
    SKILL_LEVEL_UP,
    TURRET_PLATE_DESTROYED,
    WARD_KILL,
    WARD_PLACED
}
